4
NamtrakOrganisation/MedSystem pull request #26
Opened 2022-01-10 21:32 UTC by MacWar

2022-01-11 02:00 UTC, Hoodster requested changes

2022-01-11 11:31 UTC, MacWar commented on MedSystem/Frontend/client/src/components/BookVisit/BookVisit.js
> +        if ([6, 0].includes(day)) {
It's method which get actual date, and check if the date is a day of Weekend (Saturaday or Sunday). In case it is weekend day, method assign actual date to nearest monday

2022-01-11 13:32 UTC, Hoodster commented on MedSystem/Frontend/client/src/components/BookVisit/BookVisit.js
> +        if ([6, 0].includes(day)) {
I would exclude it into another function and it would be best if you describe 6 and 0 values as variables.

2022-01-11 13:36 UTC, Hoodster commented on MedSystem/Backend/MedSystem/Core/Repositories/AccountRepository/AccountRepository.cs
> +            foreach (var user in users)
It's kinda useless code. Remember that we have LINQ and Entity Framework which allow us to avoid creating lists. Replacing it with `dbContext.Users.Where(x => x.DoctorId != null)` will give you the same result.

2022-01-11 13:39 UTC, Hoodster commented on MedSystem/Backend/MedSystem/Core/Repositories/AccountRepository/AccountRepository.cs
> +            foreach (var user in users)
Also, if you want you can get Doctor object data by adding `.Include(x => x.Doctor)` as well

2022-01-11 13:47 UTC, MacWar commented on MedSystem/Backend/MedSystem/Core/Repositories/AccountRepository/AccountRepository.cs
> +            var doctors = new List<User>();
Method returns a list of users who are doctors because on the frontend side we need information such as Name, Surname and email of the doctor, which can only be read from the User table.

2022-01-11 13:48 UTC, MacWar commented on MedSystem/Backend/MedSystem/Core/Repositories/AccountRepository/AccountRepository.cs
> +            var users = _userManager.Users.ToList();
Method returns a list of users who are doctors because on the frontend side we need information such as Name, Surname and email of the doctor, which can only be read from the User table.

2022-01-13 04:16 UTC, Hoodster approved these changes

2022-01-13 04:17 UTC, merged